# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arquivocode.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 570)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pbAdd = QtWidgets.QPushButton(self.frame)
        self.pbAdd.setGeometry(QtCore.QRect(133, 320, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pbAdd.setFont(font)
        self.pbAdd.setStyleSheet("")
        self.pbAdd.setObjectName("pbAdd")
        self.pbCalcular = QtWidgets.QPushButton(self.frame)
        self.pbCalcular.setGeometry(QtCore.QRect(500, 320, 270, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pbCalcular.setFont(font)
        self.pbCalcular.setStyleSheet("background-color: rgb(255, 124, 84);")
        self.pbCalcular.setObjectName("pbCalcular")
        self.lResultado = QtWidgets.QLabel(self.frame)
        self.lResultado.setGeometry(QtCore.QRect(30, 40, 47, 191))
        self.lResultado.setText("")
        self.lResultado.setObjectName("lResultado")
        self.leHorario = QtWidgets.QLineEdit(self.frame)
        self.leHorario.setGeometry(QtCore.QRect(340, 240, 211, 31))
        self.leHorario.setObjectName("leHorario")
        self.lResultado2 = QtWidgets.QLabel(self.frame)
        self.lResultado2.setGeometry(QtCore.QRect(90, 430, 671, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lResultado2.setFont(font)
        self.lResultado2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lResultado2.setStyleSheet("text-align: center;")
        self.lResultado2.setText("")
        self.lResultado2.setObjectName("lResultado2")
        self.lNome = QtWidgets.QLabel(self.frame)
        self.lNome.setGeometry(QtCore.QRect(340, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lNome.setFont(font)
        self.lNome.setStyleSheet("")
        self.lNome.setObjectName("lNome")
        self.leFuncionario = QtWidgets.QLineEdit(self.frame)
        self.leFuncionario.setGeometry(QtCore.QRect(340, 160, 211, 31))
        self.leFuncionario.setObjectName("leFuncionario")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(70, 410, 701, 71))
        self.textEdit.setObjectName("textEdit")
        self.botao = QtWidgets.QPushButton(self.frame)
        self.botao.setGeometry(QtCore.QRect(750, 30, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.botao.setFont(font)
        self.botao.setAutoFillBackground(False)
        self.botao.setStyleSheet("#botao{\n"
"background-color: transparent;\n"
"border-image: url(:pdfroubado.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;\n"
"}\n"
"")
        icon = QtGui.QIcon.fromTheme("pdf")
        self.botao.setIcon(icon)
        self.botao.setObjectName("botao")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(340, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2.raise_()
        self.pbAdd.raise_()
        self.pbCalcular.raise_()
        self.lResultado.raise_()
        self.leHorario.raise_()
        self.lNome.raise_()
        self.leFuncionario.raise_()
        self.textEdit.raise_()
        self.lResultado2.raise_()
        self.botao.raise_()
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Adicional Noturno"))
        self.pbAdd.setText(_translate("MainWindow", "Adicionar"))
        self.pbCalcular.setText(_translate("MainWindow", "Calcular"))
        self.lNome.setText(_translate("MainWindow", "Nome do funcionário"))
        self.botao.setText(_translate("MainWindow", "PDF"))
        self.label.setText(_translate("MainWindow", "Horário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
